# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Manifest
    url: /#manifest
    weight: 20
  - name: Solutions
    url: /#solutions
    weight: 30
  - name: Services
    url: /#Services
    weight: 40
  # - name: Resources
  #   weight: 50
  #   hasChildren: true
  # - parent: Resources
  #   name: Blog
  #   url: blog/
