# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: light
  color: indigo

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: ''
    twitter: 'GetResearchDev'
  analytics:
    google_analytics: 'G-Z41P3E8PXG'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    align: "center"
    fixed_to_top: true
    logo:
      text: "daikon"
      # Logo filename in `assets/media/` folder
      filename: "daikon.svg"
    button:
      enable: true
      text: "Parlons-en !"
      url: "mailto:contact@daikon.eco"
    show_search: true
    show_theme_chooser: true

# Site footer
footer:
  copyright:
    notice: '© {year} Alexandre Duverger EI'

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
